import { useEffect } from "react";

import "./App.css";
import reactLogo from "./assets/react-logo.svg";

const App = () => {
  // Make calls to your backend using your autogenerated API

  // If you create a model called `Blog Article`, you can find the first page of blogArticles with `useFindMany`
  // const [{ data, error, fetching}] = useFindMany(api.blogArticle);

  // Call actions on the model with `useAction`
  // const [{data, error, fetching}, runAction] = useAction(api.blogArticle.create, {
  //  "title": "a blog post title",
  //  "description": "some content",
  // });

  useEffect(() => {
    document.title = `Home - ${process.env.GADGET_PUBLIC_APP_SLUG} - Gadget`;
  }, []);

  return (
    <div className="app">
      <div className="app-content">
        <div>
          <img src={reactLogo} className="app-logo" alt="logo" />
          <div className="text">
            <p className="app-link">
              {"This page is powered by your "}
              <a href="/edit/files/frontend/App.jsx" target="_blank" rel="noreferrer">
                frontend/App.jsx
              </a>
            </p>
            <p className="environment">
              This is your <span className={process.env.GADGET_PUBLIC_APP_ENV}>{process.env.GADGET_PUBLIC_APP_ENV}</span> environment
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default App;
